name: vc_final 
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - datamash 
  - samtools 
  - bcftools 
  - bedtools 
  - htslib 
  - bwa 
  - delly 
  - alfred 
  - freebayes 
  - igv 
  - wally 
  - minimap2
  - bioconductor-genomicfeatures 
  - r-ggplot2 
  - r-reshape2 
  - bioconductor-dnacopy
  - cyvcf2 
  - numpy 
  - pysam
  - pip
  - pip:
    - gdown
